import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Baby, Measurement, Medication, SicknessEpisode, Vaccine } from '../types/models';
import { computePercentile } from './percentiles';
import { ageString } from './time';

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString([], { year: 'numeric', month: 'short', day: 'numeric' });
}

/** Builds a pediatrician-friendly one-page summary and opens the share sheet. */
export async function exportPediatricianPdf(data: {
  baby: Baby;
  measurements: Measurement[];
  vaccines: Vaccine[];
  sickness: SicknessEpisode[];
  medications: Medication[];
}): Promise<void> {
  const { baby, measurements, vaccines, sickness, medications } = data;
  const sorted = [...measurements].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  const measurementRows = sorted
    .map((m) => {
      const wPct = m.weightKg ? computePercentile('weight', baby.sex, m.weightKg, baby.dob, m.date).percentile : null;
      const hPct = m.heightCm ? computePercentile('height', baby.sex, m.heightCm, baby.dob, m.date).percentile : null;
      const headPct = m.headCm ? computePercentile('head', baby.sex, m.headCm, baby.dob, m.date).percentile : null;
      return `<tr>
        <td>${fmtDate(m.date)}</td>
        <td>${m.weightKg ? `${m.weightKg} kg (P${wPct})` : '—'}</td>
        <td>${m.heightCm ? `${m.heightCm} cm (P${hPct})` : '—'}</td>
        <td>${m.headCm ? `${m.headCm} cm (P${headPct})` : '—'}</td>
      </tr>`;
    })
    .join('');

  const vaccineRows = vaccines
    .map(
      (v) => `<tr>
        <td>${esc(v.name)} · ${esc(v.doseLabel)}</td>
        <td>${v.status === 'done' ? 'Given' : 'Due'} ${fmtDate(v.date)}</td>
        <td>${esc([v.site, v.reaction, v.notes].filter(Boolean).join(' · ') || '—')}</td>
      </tr>`
    )
    .join('');

  const sicknessRows = sickness
    .map(
      (s) => `<tr>
        <td>${esc(s.title)}</td>
        <td>${fmtDate(s.startDate)}${s.endDate ? ` – ${fmtDate(s.endDate)}` : ' (ongoing)'}</td>
        <td>${esc(s.notes ?? '—')}</td>
      </tr>`
    )
    .join('');

  const medRows = medications
    .map(
      (m) => `<tr>
        <td>${esc(m.name)}</td>
        <td>${esc(m.dose)}</td>
        <td>${esc(m.schedule)}${m.prn ? ' (PRN)' : m.ongoing ? ' (ongoing)' : ''}</td>
      </tr>`
    )
    .join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body { font-family: -apple-system, Helvetica, sans-serif; color: #43382F; padding: 24px; }
    h1 { font-size: 22px; margin-bottom: 2px; }
    .sub { color: #7C6E5F; font-size: 13px; margin-bottom: 20px; }
    h2 { font-size: 15px; margin: 22px 0 6px; border-bottom: 2px solid #E98862; padding-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
    th { text-align: left; color: #9B8B7D; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; padding: 6px 8px; }
    td { padding: 6px 8px; border-top: 1px solid #F2E8DA; }
    .footer { margin-top: 28px; font-size: 10.5px; color: #B39F8D; }
  </style></head><body>
    <h1>${esc(baby.name)} — Health &amp; Growth Summary</h1>
    <div class="sub">Born ${fmtDate(baby.dob)} · ${ageString(baby.dob)} · birth weight ${baby.birthWeightKg} kg · birth length ${baby.birthLengthCm} cm</div>

    <h2>Growth measurements</h2>
    <table><tr><th>Date</th><th>Weight</th><th>Height</th><th>Head</th></tr>${measurementRows}</table>

    <h2>Vaccines</h2>
    <table><tr><th>Vaccine</th><th>Status</th><th>Notes</th></tr>${vaccineRows}</table>

    <h2>Sickness &amp; symptoms</h2>
    <table><tr><th>Episode</th><th>Dates</th><th>Notes</th></tr>${sicknessRows || '<tr><td colspan="3">None recorded</td></tr>'}</table>

    <h2>Medications</h2>
    <table><tr><th>Medicine</th><th>Dose</th><th>Schedule</th></tr>${medRows || '<tr><td colspan="3">None recorded</td></tr>'}</table>

    <div class="footer">Generated by Prince Baby Tracker on ${new Date().toLocaleDateString([], { year: 'numeric', month: 'long', day: 'numeric' })}. Percentiles are WHO growth-standard approximations — not a clinical measurement.</div>
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `${baby.name} — health summary` });
  } else {
    // e.g. web: fall back to the print dialog
    await Print.printAsync({ html });
  }
}
